networks:
  test:

services:
  redis-test:
    image: redis:latest
    container_name: redis-test
    networks:
      - test

  postgres-test:
    image: postgres:16
    container_name: botanic-postgres-test
    env_file:
      - backend/.env.test
    networks:
      - test
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5

  app-test:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
      args:
        ENV: test
    env_file: "./backend/.env.test"
    command: sh -c "
      alembic upgrade head &&
      if [ -n \"$$PYTEST_PATH\" ]; then
        coverage run --source='.' -m pytest -s --rootdir=/app/ --disable-pytest-warnings $$PYTEST_PATH;
      else
        coverage run --source='.' -m pytest -s --rootdir=/app/ --disable-pytest-warnings;
      fi &&
      coverage html -d /htmlcov"
    volumes:
      - ./backend/htmlcov:/htmlcov
    depends_on:
      - postgres-test
    networks:
      - test