"""add_user_discounts

Revision ID: 0653c0ebc9e0
Revises: 7ada20af55bb
Create Date: 2025-05-05 10:08:07.941274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0653c0ebc9e0'
down_revision: Union[str, None] = '7ada20af55bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_discounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_level', sa.Enum('BRONZE', 'SILVER', 'GOLD', 'NONE', name='userdiscountlevel'), nullable=False),
    sa.Column('last_purchase_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_discounts')
    # ### end Alembic commands ###
