"""change product image fields to ImageType

Revision ID: 1d0b6c64b3fb
Revises: d121311d58d6
Create Date: 2025-08-30 19:39:11.076222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d0b6c64b3fb'
down_revision: Union[str, None] = 'd121311d58d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'background_image_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='URL фоновой картинки товара',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'background_image_url',
               existing_type=sa.VARCHAR(length=500),
               comment='URL фоновой картинки товара',
               existing_nullable=True)
    # ### end Alembic commands ###
