"""add_additional_description_to_product

Revision ID: 36db84fced6b
Revises: 86c603905b8c
Create Date: 2025-02-10 03:30:36.748175

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '36db84fced6b'
down_revision: Union[str, None] = '86c603905b8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('additional_description', sa.Text(), nullable=True,
                                        comment='Дополнительное описание товара'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'additional_description')
    # ### end Alembic commands ###
