"""order_add_new_fields

Revision ID: 3f77239ca57e
Revises: f7b96c620a0f
Create Date: 2025-04-11 15:28:30.426324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f77239ca57e'
down_revision: Union[str, None] = 'f7b96c620a0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_warehouse_address', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('delivery_point', sa.String(length=15), nullable=True))
    op.add_column('orders', sa.Column('delivery_to_location', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('orders', sa.Column('delivery_comment', sa.String(), nullable=True))
    op.drop_column('orders', 'delivery_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_address', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('orders', 'delivery_comment')
    op.drop_column('orders', 'delivery_to_location')
    op.drop_column('orders', 'delivery_point')
    op.drop_column('orders', 'delivery_warehouse_address')
    # ### end Alembic commands ###
