"""updated_product_model

Revision ID: 3fbc811daa2b
Revises: 8846d495538a
Create Date: 2025-02-06 09:10:30.711323

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3fbc811daa2b'
down_revision: Union[str, None] = '8846d495538a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('products', sa.Column('sku', sa.String(length=50), nullable=True))
    op.alter_column('products', 'description',
                    existing_type=sa.VARCHAR(),
                    type_=sa.Text(),
                    existing_nullable=True)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_unique_constraint(None, 'products', ['sku'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.alter_column('products', 'description',
                    existing_type=sa.Text(),
                    type_=sa.VARCHAR(),
                    existing_nullable=True)
    op.drop_column('products', 'sku')
    op.drop_column('products', 'image_url')
    op.drop_column('products', 'category')
    # ### end Alembic commands ###
