"""add_payments_table

Revision ID: 40ecf7981ee3
Revises: 7f10e31474a7
Create Date: 2025-03-07 06:27:41.413033

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '40ecf7981ee3'
down_revision: Union[str, None] = '7f10e31474a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('order_id', sa.UUID(), nullable=False),
                    sa.Column('provider', sa.String(), nullable=False, comment='Название платежной системы'),
                    sa.Column('provider_payment_id', sa.String(), nullable=True,
                              comment='ID платежа в системе провайдера'),
                    sa.Column('status', sa.String(), nullable=False),
                    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
                    sa.Column('currency', sa.String(), nullable=False),
                    sa.Column('payment_method', sa.String(), nullable=True, comment='Метод оплаты'),
                    sa.Column('payment_data', sa.JSON(), nullable=True, comment='Дополнительные данные об оплате'),
                    sa.Column('confirmation_url', sa.String(), nullable=True, comment='URL для подтверждения оплаты'),
                    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True, comment='Дата и время оплаты'),
                    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True,
                              comment='Дата и время возврата'),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    # ### end Alembic commands ###
