"""add productimage model

Revision ID: 56a073f3369c
Revises: 1d0b6c64b3fb
Create Date: 2025-08-31 04:53:07.026214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app

from fastapi_storages import FileSystemStorage
from app.core.settings import settings

storage = FileSystemStorage(path=str(settings.MEDIA_DIR / "products"))

# revision identifiers, used by Alembic.
revision: str = '56a073f3369c'
down_revision: Union[str, None] = '1d0b6c64b3fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('image_url', app.models.custom_types.ResilientImageType(storage=storage), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('products', 'additional_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Дополнительное описание товара',
               existing_nullable=True)
    op.alter_column('products', 'weight',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Вес в граммах',
               existing_nullable=True)
    op.alter_column('products', 'length',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Длина в мм',
               existing_nullable=True)
    op.alter_column('products', 'width',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Ширина в мм',
               existing_nullable=True)
    op.alter_column('products', 'height',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Высота в мм',
               existing_nullable=True)
    op.drop_column('products', 'additional_images_urls')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('additional_images_urls', postgresql.ARRAY(sa.VARCHAR()), server_default=sa.text("'{}'::character varying[]"), autoincrement=False, nullable=True, comment='URLs дополнительных изображений товара'))
    op.alter_column('products', 'height',
               existing_type=sa.INTEGER(),
               comment='Высота в мм',
               existing_nullable=True)
    op.alter_column('products', 'width',
               existing_type=sa.INTEGER(),
               comment='Ширина в мм',
               existing_nullable=True)
    op.alter_column('products', 'length',
               existing_type=sa.INTEGER(),
               comment='Длина в мм',
               existing_nullable=True)
    op.alter_column('products', 'weight',
               existing_type=sa.INTEGER(),
               comment='Вес в граммах',
               existing_nullable=True)
    op.alter_column('products', 'additional_description',
               existing_type=sa.TEXT(),
               comment='Дополнительное описание товара',
               existing_nullable=True)
    op.drop_table('product_images')
    # ### end Alembic commands ###
