"""add header_image to Product and remove ProductImage model

Revision ID: 59b90289b9ff
Revises: 56a073f3369c
Create Date: 2025-09-01 19:54:21.881398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from fastapi_storages import FileSystemStorage
from app.core.settings import settings
from app.models.custom_types import ResilientImageType

# revision identifiers, used by Alembic.
revision: str = '59b90289b9ff'
down_revision: Union[str, None] = '56a073f3369c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


storage = FileSystemStorage(path=str(settings.MEDIA_DIR / "products"))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_images')
    op.add_column('products', sa.Column('header_image_url', ResilientImageType(storage=storage), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'header_image_url')
    op.create_table('product_images',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_images_product_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='product_images_pkey')
    )
    # ### end Alembic commands ###
