"""change_referral_payout_request

Revision ID: 6b51f4d9f76e
Revises: 0be69a03b282
Create Date: 2025-05-10 01:13:34.484503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b51f4d9f76e'
down_revision: Union[str, None] = '0be69a03b282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referral_payout_requests', sa.Column('bank_code', sa.String(length=11), nullable=False))
    op.add_column('referral_payout_requests', sa.Column('account_number', sa.String(length=34), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referral_payout_requests', 'account_number')
    op.drop_column('referral_payout_requests', 'bank_code')
    # ### end Alembic commands ###
