"""delete_referral_balance_and_add_bonus_reverted_at

Revision ID: 7ada20af55bb
Revises: 94217c36bac4
Create Date: 2025-05-01 17:33:01.988996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ada20af55bb'
down_revision: Union[str, None] = '94217c36bac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referral_bonuses', sa.Column('reverted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('referrals', 'balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrals', sa.Column('balance', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('referral_bonuses', 'reverted_at')
    # ### end Alembic commands ###
