"""order_add_delivery_tariff_code

Revision ID: 7d2eedfdadbd
Revises: 3f77239ca57e
Create Date: 2025-04-12 14:00:30.459864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d2eedfdadbd'
down_revision: Union[str, None] = '3f77239ca57e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_tariff_code', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_tariff_code')
    # ### end Alembic commands ###
