"""add_background_image_url

Revision ID: 7f10e31474a7
Revises: 43072af344c0
Create Date: 2025-02-18 11:27:23.142416

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7f10e31474a7'
down_revision: Union[str, None] = '43072af344c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('background_image_url', sa.String(length=500), nullable=True,
                                        comment='URL фоновой картинки товара'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'background_image_url')
    # ### end Alembic commands ###
