"""add_product_additional_images

Revision ID: 86c603905b8c
Revises: 6f534ebcf835
Create Date: 2025-02-09 12:35:45.834190

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86c603905b8c'
down_revision: Union[str, None] = '6f534ebcf835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products',
                  sa.Column('additional_images_urls', postgresql.ARRAY(sa.String()), server_default='{}', nullable=True,
                            comment='URLs дополнительных изображений товара'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'additional_images_urls')
    # ### end Alembic commands ###
