"""add_product_dimensions_and_track_number

Revision ID: aba0c090356b
Revises: 83ae34738c95
Create Date: 2025-08-24 03:58:30.176159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aba0c090356b'
down_revision: Union[str, None] = '83ae34738c95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('track_number', sa.String(), nullable=True, comment='Трек-номер СДЭК'))
    op.add_column('products', sa.Column('weight', sa.Integer(), nullable=True, comment='Вес в граммах'))
    op.add_column('products', sa.Column('length', sa.Integer(), nullable=True, comment='Длина в мм'))
    op.add_column('products', sa.Column('width', sa.Integer(), nullable=True, comment='Ширина в мм'))
    op.add_column('products', sa.Column('height', sa.Integer(), nullable=True, comment='Высота в мм'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'height')
    op.drop_column('products', 'width')
    op.drop_column('products', 'length')
    op.drop_column('products', 'weight')
    op.drop_column('orders', 'track_number')
    # ### end Alembic commands ###
