"""add_constraint_to_user_delivery_point

Revision ID: ad7f4f335de7
Revises: 58a76126d623
Create Date: 2025-04-09 17:17:08.395480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad7f4f335de7'
down_revision: Union[str, None] = '58a76126d623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cdek_delivery_points', ['id'])
    op.create_unique_constraint('uix_user_cdek_dp', 'user_delivery_points', ['user_id', 'cdek_delivery_point_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_user_cdek_dp', 'user_delivery_points', type_='unique')
    op.drop_constraint(None, 'cdek_delivery_points', type_='unique')
    # ### end Alembic commands ###
