"""Add ondelete cascade for user relations

Revision ID: d121311d58d6
Revises: 357a5db4e709
Create Date: 2025-08-24 12:34:29.568689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd121311d58d6'
down_revision: Union[str, None] = '357a5db4e709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_payout_requests_user_id', 'payout_requests', type_='foreignkey')
    op.create_foreign_key(None, 'payout_requests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'accepted_terms',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'accepted_terms',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'payout_requests', type_='foreignkey')
    op.create_foreign_key('fk_payout_requests_user_id', 'payout_requests', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
