"""add_constraint_to_user_address

Revision ID: f7b96c620a0f
Revises: ad7f4f335de7
Create Date: 2025-04-09 17:21:28.275802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7b96c620a0f'
down_revision: Union[str, None] = 'ad7f4f335de7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_user_address', 'user_addresses', ['user_id', 'address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_user_address', 'user_addresses', type_='unique')
    # ### end Alembic commands ###
