# Workflow работает так:
# 
# При создании/обновлении PR в main: запускаются только линтеры и тесты 
# При прямом пуше в main: запускаются линтеры и тесты, затем деплой (если проверки прошли)
# При мерже PR в main: запускаются линтеры и тесты, затем деплой (если проверки прошли)
name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-frontend:
    name: Lint Frontend Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/app/package-lock.json

      - name: Install dependencies
        working-directory: frontend/app
        run: npm ci

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Run frontend linting
        run: just lint-frontend

  test-backend:
    name: Run Backend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Run backend tests
        run: just test-backend

  test-frontend:
    name: Run Frontend Tests
    runs-on: ubuntu-latest
    needs: [lint-frontend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/app/package-lock.json

      - name: Install dependencies
        working-directory: frontend/app
        run: npm ci

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Run frontend tests
        working-directory: frontend
        run: just test-frontend

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [lint-frontend, test-backend, test-frontend]
    # Деплой запускается только при пуше в main (включая мерж PR)
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: 46.149.70.152
          SSH_USER: root
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github
          chmod 600 ~/.ssh/github
          cat >>~/.ssh/config <<END
          Host target
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/github
            LogLevel ERROR
            StrictHostKeyChecking no
          END

      - name: Run Deploy
      # Для работы git pull необходимо настроить Deploy Key на сервере (см. README)
        run: |
          ssh target "
            cd /root/bottec-botanic-bay &&
            git pull origin main &&
            docker compose -f docker-compose.prod.yml down &&
            docker system prune -f -a &&
            docker volume rm tg_store_frontend_dist || true &&
            docker compose -f docker-compose.prod.yml up -d --build
          "
